import XCTest

final class PlanDashboardViewSourceTests: XCTestCase {
    func testGoalComposerUsesWrappingStatusChipsInsteadOfSingleRowSegmentedControl() throws {
        let source = try String(
            contentsOfFile: "/Users/xiakaiyang/Documents/New project/Apps/FocusSessionApp/UI/Plan/PlanDashboardView.swift",
            encoding: .utf8
        )

        XCTAssertTrue(source.contains("goalStatusFlowPicker"))
        XCTAssertTrue(source.contains("goalStatusColumns"))
        XCTAssertTrue(source.contains("goalStatusChip(for: status)"))
        XCTAssertTrue(source.contains("LazyVGrid(columns: goalStatusColumns"))
        XCTAssertFalse(source.contains("options: PlanGoalStatus.allCases"))
    }

    func testMonthTimelineUsesMonthlyAxisMarksAndTodayRuleUsesGold() throws {
        let source = try String(
            contentsOfFile: "/Users/xiakaiyang/Documents/New project/Apps/FocusSessionApp/UI/Plan/PlanDashboardView.swift",
            encoding: .utf8
        )

        XCTAssertTrue(source.contains("AxisMarks(values: .stride(by: .month))"))
        XCTAssertTrue(source.contains("AxisMarks(values: .stride(by: .weekOfYear))"))
        XCTAssertTrue(source.contains("AxisMarks(values: .stride(by: .day, count: 3))"))
        XCTAssertTrue(source.contains("Color(red: 0.90, green: 0.73, blue: 0.18)"))
        XCTAssertTrue(source.contains(".chartYAxis(.hidden)"))
        XCTAssertTrue(source.contains(".chartPlotStyle"))
        XCTAssertTrue(source.contains("TimelineHorizontalScrollContainer"))
        XCTAssertTrue(source.contains("hasHorizontalScroller = true"))
        XCTAssertTrue(source.contains("hasVerticalScroller = false"))
        XCTAssertTrue(source.contains("autohidesScrollers = false"))
        XCTAssertTrue(source.contains("scrollerStyle = .legacy"))
        XCTAssertTrue(source.contains(".padding(.top, 24)"))
        XCTAssertTrue(source.contains(".padding(.top, PlanTimelinePresentation.monthAxisLabelTopPadding)"))
        XCTAssertTrue(source.contains(".chartYScale(range: .plotDimension(startPadding: 20, endPadding: 64))"))
        XCTAssertTrue(source.contains("PlanTimelinePresentation.monthAxisLabel"))
        XCTAssertTrue(source.contains("PlanTimelinePresentation.chartHeight(forGoalCount: viewModel.timelineGoals.count)"))
        XCTAssertTrue(source.contains("PlanTimelinePresentation.chartContentWidthMultiplier(forVisibleMonthSpan: viewModel.visibleMonthSpanForPresentation)"))
        XCTAssertTrue(source.contains("PlanTimelinePresentation.axisDetailLevel(forVisibleMonthSpan: viewModel.visibleMonthSpanForPresentation)"))
        XCTAssertTrue(source.contains("PlanTimelinePresentation.labelPlacement"))
        XCTAssertTrue(source.contains(".chartOverlay"))
        XCTAssertTrue(source.contains("TimelineZoomTrackingSurface"))
        XCTAssertTrue(source.contains("TimelineZoomInteractionGate"))
        XCTAssertTrue(source.contains("TimelineZoomScrollRouting.route("))
        XCTAssertTrue(source.contains("matching: [.leftMouseDown, .rightMouseDown, .otherMouseDown]"))
        XCTAssertTrue(source.contains("matching: [.scrollWheel]"))
        XCTAssertTrue(source.contains("override func hitTest(_ point: NSPoint) -> NSView?"))
        XCTAssertTrue(source.contains("deactivateIfNeeded"))
        XCTAssertTrue(source.contains(".clipShape(RoundedRectangle(cornerRadius: 24, style: .continuous))"))
        XCTAssertTrue(source.contains("Overall Progress"))
        XCTAssertTrue(source.contains("Subtasks"))
        XCTAssertTrue(source.contains("goal.subtasks"))
        XCTAssertTrue(source.contains("Show Subtasks"))
        XCTAssertTrue(source.contains("Hide Subtasks"))
        XCTAssertTrue(source.contains("expandedGoalIDs"))
        XCTAssertTrue(source.contains("@State private var isNoMansLandExpanded = false"))
        XCTAssertTrue(source.contains("toggleGoalSubtasks"))
        XCTAssertTrue(source.contains("toggleNoMansLand()"))
        XCTAssertTrue(source.contains("chevron.up"))
        XCTAssertTrue(source.contains("chevron.down"))
        XCTAssertTrue(source.contains("chevron.right"))
        XCTAssertTrue(source.contains("goalPrimaryDetails(for: goal)"))
        XCTAssertTrue(source.contains("goalSubtasksExpansionPanel"))
        XCTAssertTrue(source.contains("goalSubtaskGridColumns"))
        XCTAssertTrue(source.contains("LazyVGrid(columns: goalSubtaskGridColumns"))
        XCTAssertTrue(source.contains("viewModel.activeGoals.isEmpty"))
        XCTAssertTrue(source.contains("ForEach(Array(viewModel.activeGoals.enumerated())"))
        XCTAssertTrue(source.contains("@ObservedObject private var preferencesStore: AppPreferencesStore"))
        XCTAssertTrue(source.contains("preferencesStore.preferences.planGoalLaunchExpansion"))
        XCTAssertTrue(source.contains("applyGoalSubtaskLaunchPreference()"))
        XCTAssertTrue(source.contains(".onAppear"))
        XCTAssertTrue(source.contains("viewModel.activeGoals.filter(\\.hasSubtasks).map(\\.id)"))
        XCTAssertTrue(source.contains("Text(\"No Man's Land\")"))
        XCTAssertTrue(source.contains("viewModel.noMansLandGoals"))
        XCTAssertTrue(source.contains("if isNoMansLandExpanded"))
        XCTAssertTrue(source.contains("goalRow(goal, readOnly: false)"))
        XCTAssertTrue(source.contains("goalRow(goal, readOnly: true)"))
        XCTAssertTrue(source.contains("moveActiveGoal"))
        XCTAssertTrue(source.contains("draggedGoalID"))
        XCTAssertTrue(source.contains("scrollDisabled(draggedGoalID != nil)"))
        XCTAssertTrue(source.contains("highPriorityGesture"))
        XCTAssertTrue(source.contains("DragGesture(minimumDistance: 4, coordinateSpace: .named(goalListCoordinateSpace))"))
        XCTAssertTrue(source.contains("handleGoalDragChanged"))
        XCTAssertTrue(source.contains("handleGoalDragEnded"))
        XCTAssertTrue(source.contains("dragOffset(for: goal)"))
        XCTAssertTrue(source.contains("goalRowFrames"))
        XCTAssertTrue(source.contains("dragStartFrames"))
        XCTAssertTrue(source.contains("goalSubtaskCard(for: goal, subtask: subtask)"))
        XCTAssertTrue(source.contains("goalAddSubtaskButton(for: goal)"))
        XCTAssertTrue(source.contains("expandGoalSubtasks(for: goal)"))
        XCTAssertTrue(source.contains("draggedSubtaskID"))
        XCTAssertTrue(source.contains("draggedSubtaskTranslation"))
        XCTAssertTrue(source.contains("subtaskCardFrames"))
        XCTAssertTrue(source.contains("subtaskCardFrameReader"))
        XCTAssertTrue(source.contains("handleSubtaskDragChanged"))
        XCTAssertTrue(source.contains("handleSubtaskDragEnded"))
        XCTAssertTrue(source.contains("subtaskDragOffset"))
        XCTAssertTrue(source.contains("viewModel.moveSubtask("))
        XCTAssertTrue(source.contains("VStack(spacing: 0) {\n                Spacer(minLength: 0)\n                goalAddSubtaskButton(for: goal)\n                Spacer(minLength: 0)\n            }\n            .frame(maxWidth: .infinity, maxHeight: .infinity)\n            .frame(minHeight: 64)"))
        XCTAssertTrue(source.contains("goalSubtaskMetricText(for: subtask)"))
        XCTAssertTrue(source.contains("goalSubtaskMetricBlock"))
        XCTAssertTrue(source.contains("goalSubtaskSecondaryBlock"))
        XCTAssertTrue(source.contains("subtaskCardProgressSurface(progress: Double(progressPercent) / 100, tint: tint)"))
        XCTAssertTrue(source.contains("goalProgressFillEnd(for: goal)"))
        XCTAssertTrue(source.contains("goalTimelineStatusMarker(for: goal)"))
        XCTAssertTrue(source.contains("Image(systemName: \"xmark\")"))
        XCTAssertTrue(source.contains("statusColor(for: goal.status).opacity(0.18)"))
        XCTAssertTrue(source.contains("statusColor(for: goal.status).opacity(0.52)"))
        XCTAssertTrue(source.contains("chartYScale(domain: viewModel.timelineGoals.map(\\.timelineRowID))"))
        XCTAssertTrue(source.contains("goal.status == .unfinished"))
        XCTAssertTrue(source.contains(".frame(width: 30, height: 30)"))
        XCTAssertTrue(source.contains(".stroke(tint.opacity(0.22), lineWidth: 1)"))
        XCTAssertTrue(source.contains(".frame(maxWidth: .infinity, minHeight: 64, alignment: .leading)"))
        XCTAssertTrue(source.contains(".padding(8)"))
        XCTAssertTrue(source.contains("contextMenu"))
        XCTAssertTrue(source.contains("plus"))
        XCTAssertTrue(source.contains("viewModel.progressPercent(for: goal)"))
        XCTAssertTrue(source.contains("viewModel.currentValue(for: subtask)"))
        XCTAssertTrue(source.contains("viewModel.linkedTaskCount(for: subtask)"))
        XCTAssertTrue(source.contains("viewModel.presentCreateSubtaskSheet(for: goal)"))
        XCTAssertTrue(source.contains("viewModel.presentEditSubtaskSheet(for: goal, subtask: subtask)"))
        XCTAssertTrue(source.contains("private func opticallyCenteredPlusIcon(size: CGFloat, tint: Color)"))
        XCTAssertTrue(source.contains(".offset(y: 0.5)"))
        XCTAssertTrue(source.contains("opticallyCenteredPlusIcon(size: 10, tint: tint)"))
        XCTAssertTrue(source.contains("opticallyCenteredPlusIcon(size: 13, tint: tint)"))
        XCTAssertTrue(source.contains("NewT"))
        XCTAssertTrue(source.contains("LinkT"))
        XCTAssertTrue(source.contains("linkedTaskActionButtonLabel("))
        XCTAssertTrue(source.contains("calendar.badge.plus"))
        XCTAssertTrue(source.contains("link.badge.plus"))
        XCTAssertTrue(source.contains("Linked Today Tasks"))
        XCTAssertTrue(source.contains("No current Today tasks or repeating tasks are available to link."))
        XCTAssertTrue(source.contains(".frame(maxWidth: .infinity, minHeight: 46, alignment: .leading)"))
        XCTAssertTrue(source.contains(".lineLimit(1)"))
        XCTAssertTrue(source.contains(".minimumScaleFactor(0.9)"))
        XCTAssertTrue(source.contains("Subtask Metrics"))
        XCTAssertTrue(source.contains("PlanGoalSubtaskTrackingMode.allCases"))
        XCTAssertTrue(source.contains("viewModel.subtaskDraftTrackingMode"))
        XCTAssertTrue(source.contains("viewModel.subtaskDraftEstimatedProgressPercent"))
        XCTAssertTrue(source.contains("viewModel.setSubtaskDraftEstimatedPreviewProgress"))
        XCTAssertTrue(source.contains("Estimated"))
        XCTAssertTrue(source.contains("Quantified"))
        XCTAssertTrue(source.contains("Allocation Across Subtasks"))
        XCTAssertTrue(source.contains("Allocated"))
        XCTAssertTrue(source.contains("Remaining"))
        XCTAssertTrue(source.contains("estimatedCurrentCompletionField"))
        XCTAssertTrue(source.contains("DraggableGoalProgressBar("))
        XCTAssertTrue(source.contains("goalComposerAllocationSection"))
        XCTAssertTrue(source.contains("viewModel.goalComposerSubtaskShareRows"))
        XCTAssertTrue(source.contains("viewModel.setGoalComposerSubtaskShareText"))
        XCTAssertTrue(source.contains("viewModel.isPresentingSubtaskSheet"))
        XCTAssertTrue(source.contains(".frame(maxWidth: .infinity, alignment: .leading)"))
        XCTAssertTrue(source.contains("viewModel.linkableTasks.isEmpty"))
        XCTAssertTrue(source.contains("anchor: .topTrailing"))
        XCTAssertTrue(source.contains("if viewModel.subtaskDraftTrackingMode == .quantified"))
        XCTAssertTrue(source.contains("Convert this subtask to Quantified to link Today tasks."))
        XCTAssertTrue(source.contains("if viewModel.isEditingGoal"))
        XCTAssertTrue(source.contains("Button(\"Move Left\")"))
        XCTAssertTrue(source.contains("Button(\"Move Right\")"))
        XCTAssertTrue(source.contains("Button(\"Move Left\") {\n                    animatedSubtaskReorder {"))
        XCTAssertTrue(source.contains("Button(\"Move Right\") {\n                    animatedSubtaskReorder {"))
        XCTAssertTrue(source.contains("private func animatedSubtaskReorder(_ action: () -> Void)"))
        XCTAssertTrue(source.contains("viewModel.moveSubtaskLeft("))
        XCTAssertTrue(source.contains("viewModel.moveSubtaskRight("))
        XCTAssertTrue(source.contains(".padding(.top, PlanTimelinePresentation.timelineCardTopPadding)"))
        XCTAssertTrue(source.contains(".padding(.bottom, PlanTimelinePresentation.timelineCardBottomPadding)"))
        XCTAssertTrue(source.contains(".padding(.bottom, 14)"))
        XCTAssertFalse(source.contains("completedGoalsSection"))
        XCTAssertFalse(source.contains("Button(isExpanded ? \"Hide Subtasks\" : \"Show Subtasks\")"))
        XCTAssertFalse(source.contains("goalSubtaskSegmentLabels(for: goal)"))
        XCTAssertFalse(source.contains("goalSubtaskContributionBar(for: goal)"))
        XCTAssertFalse(source.contains("subtaskContributionGradient(for: goal.status)"))
        XCTAssertFalse(source.contains("subtaskContributionDividerColor"))
        XCTAssertFalse(source.contains("subtaskCardGradient(for: goal.status)"))
        XCTAssertFalse(source.contains("viewModel.goals.isEmpty"))
        XCTAssertFalse(source.contains("ForEach(Array(viewModel.goals.enumerated())"))
        XCTAssertFalse(source.contains("subtaskCardSurfaceFill(for: goal.status)"))
        XCTAssertFalse(source.contains(".frame(maxWidth: .infinity, minHeight: 120, alignment: .leading)\n        .padding(14)"))
        XCTAssertFalse(source.contains("Color(red: 0.96, green: 0.94, blue: 0.90)"))
        XCTAssertFalse(source.contains("Color(red: 0.94, green: 0.92, blue: 0.88)"))
        XCTAssertFalse(source.contains(".foregroundStyle(statusColor(for: goal.status))"))
        XCTAssertFalse(source.contains(".opacity(goal.status == .completed ? 0.60 : 0.88)"))
        XCTAssertFalse(source.contains(".frame(maxWidth: .infinity, minHeight: 148, alignment: .leading)\n        .padding(18)"))
        XCTAssertFalse(source.contains("linked Today tasks"))
        XCTAssertFalse(source.contains(".frame(maxWidth: 320, alignment: .leading)"))
        XCTAssertFalse(source.contains(".frame(maxWidth: 360, alignment: .leading)"))
        XCTAssertFalse(source.contains(".frame(maxWidth: .infinity, alignment: .trailing)"))
        XCTAssertFalse(source.contains(".transition(.opacity.combined(with: .move(edge: .top)))"))
        XCTAssertFalse(source.contains("options: PlanTimelineScale.allCases"))
        XCTAssertFalse(source.contains("override func mouseDown(with event: NSEvent)"))
        XCTAssertFalse(source.contains("override func scrollWheel(with event: NSEvent)"))
        XCTAssertFalse(
            source.contains(
                ".padding(.horizontal, 16)\n        .padding(.vertical, 18)\n        .background(AppCardSurface(style: .standard, cornerRadius: 24))"
            )
        )
        XCTAssertFalse(source.contains("TimelineZoomTrackingSurface { deltaY, location in"))
        XCTAssertFalse(source.contains("ScrollView(.horizontal, showsIndicators: true)"))
        XCTAssertFalse(source.contains(".padding(.bottom, 22)"))
        XCTAssertFalse(source.contains(".padding(.bottom, 18)"))
        XCTAssertFalse(source.contains(".padding(.bottom, 34)"))
        XCTAssertFalse(source.contains(".padding(.top, 8)"))
        XCTAssertFalse(source.contains(".padding(.top, 10)"))
        XCTAssertFalse(source.contains(".padding(.bottom, 12)"))
        XCTAssertFalse(source.contains(".chartYScale(range: .plotDimension(startPadding: 20, endPadding: 36))"))
        XCTAssertFalse(source.contains("CGFloat(max(240, viewModel.timelineGoals.count * 44 + 100))"))
        XCTAssertFalse(source.contains("goalComposerSubtasksSection"))
        XCTAssertFalse(source.contains("viewModel.newGoalSubtasks"))
        XCTAssertFalse(source.contains("goalAddSubtaskCard(for: goal)"))
        XCTAssertFalse(source.contains("square.stack.3d.up"))
        XCTAssertFalse(source.contains("plus.circle.fill"))
        XCTAssertFalse(source.contains("\"+ Add Subtask\""))
        XCTAssertFalse(source.contains("Define the quantified target, then attach Today tasks whose completed contributions update progress automatically."))
        XCTAssertFalse(source.contains("Total must equal 100%"))
        XCTAssertFalse(source.contains("if viewModel.subtaskDraftTrackingMode == .estimated {\n                        AppPromptedTextField("))
        XCTAssertFalse(source.contains("viewModel.focusGoal(goal)\n        }"))
        XCTAssertFalse(source.contains("scrollProxy.scrollTo"))
        XCTAssertFalse(source.contains("isFocused = viewModel.focusedGoalID == goal.id"))
        XCTAssertFalse(source.contains("viewModel.completedGoals"))
        XCTAssertFalse(source.contains("New Today Task"))
        XCTAssertFalse(source.contains("viewModel.subtaskSiblingShareRows"))
        XCTAssertFalse(source.contains("viewModel.setSiblingGoalShareText"))
    }

    func testQuantifiedSubtaskPlusButtonUsesInlineIncrementInsteadOfAlwaysOpeningEditor() throws {
        let source = try String(
            contentsOfFile: "/Users/xiakaiyang/Documents/New project/Apps/FocusSessionApp/UI/Plan/PlanDashboardView.swift",
            encoding: .utf8
        )

        XCTAssertTrue(source.contains("if subtask.trackingMode == .quantified"))
        XCTAssertTrue(source.contains("viewModel.incrementSubtaskValue(for: goal, subtask: subtask)"))
        XCTAssertTrue(
            source.contains(
                ".help(subtask.trackingMode == .quantified ? \"Add 1 to current value\" : \"Edit subtask and manage linked tasks\")"
            )
        )
    }
}
